version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: my_redis
    ports:
      - "6380:6379"
    restart: always

  postgres:
    image: postgres:17
    container_name: tele_postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - ./db/socone_telegram_bot.sql:/docker-entrypoint-initdb.d/socone_telegram_bot.sql
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5434:5432"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tele_bot_socone
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    restart: always
