CREATE TABLE "staff_accounts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "telegram_account_name" VARCHAR NOT NULL,
  "full_name" VARCHAR NOT NULL,
  "phone" VARCHAR UNIQUE,
  "company_email" VARCHAR UNIQUE NOT NULL,
  "address" VARCHAR,
  "district" VARCHAR,
  "province" VARCHAR,
  "day_of_birth" DATE,
  "gender" VARCHAR(6),
  "level" VARCHAR,
  "created_at" TIMESTAMPTZ DEFAULT (NOW()),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR UNIQUE NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT (NOW()),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "staff_roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "staff_account_id" INTEGER NOT NULL,
  "role_id" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT (NOW()),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT "staff_roles_staff_account_id_fkey" 
    FOREIGN KEY ("staff_account_id") 
    REFERENCES "staff_accounts" ("id") 
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  CONSTRAINT "staff_roles_role_id_fkey" 
    FOREIGN KEY ("role_id") 
    REFERENCES "roles" ("id") 
    ON DELETE RESTRICT 
    ON UPDATE CASCADE
);

CREATE TABLE "staff_devices" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "staff_id" INTEGER UNIQUE NOT NULL,
  "mac_address" VARCHAR(17),
  "created_at" TIMESTAMPTZ DEFAULT (NOW()),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT "staff_devices_staff_id_fkey" 
    FOREIGN KEY ("staff_id") 
    REFERENCES "staff_accounts" ("id") 
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);

CREATE TABLE "staff_attendances_work" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "staff_id" INTEGER NOT NULL,
  "check_in_time" TIMESTAMPTZ NOT NULL,   -- Sử dụng TIMESTAMPTZ thay vì DATETIME
  "check_out_time" TIMESTAMPTZ,          -- Sử dụng TIMESTAMPTZ thay vì DATETIME
  "type_work" VARCHAR(30),
  "created_at" TIMESTAMPTZ DEFAULT (NOW()),
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT "staff_attendances_work_staff_id_fkey" 
    FOREIGN KEY ("staff_id") 
    REFERENCES "staff_accounts" ("id") 
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);
